### ISSUE TITLE
griefclient : some features doesn't works at all, otgher works in a weird way, and another problems

### ISSUE THREAD

**Issue by jack652** [Hellsing/ModAPI-Mods#10]
-aura : doesn't work at all

-sphere : doesn't work at all

-killing players in the "players" tab : doesn't work at all

-destroying every building with keybind : doesn't work at all

-destroying every tree with keybind : doesn't work at all

-insta build with keybind : works weirdly, it works if i get far enough from structures (and then it SOMETIMES works) (also it doesn't work in multiplayer)

-when i go in multiplayer i can't destroy anyone's base, nor hurt players

-i can't cut any tree neither in singleplayer nor in multiplayer

-i can't build anything in multiplayer

i can't fix any traps in multiplayer

**Comment by jack652** [comment]
also for some reason opening  the menu with a keybind just stopped working like 5 minutes ago for me

**Comment by Maj-ew** [comment]
also when you are host the trees would disappear when you are near them and when you are not host you can't even destroy trees even though I didn't change any option and even when I turned everything off I couldn't hit trees anyway
