### ISSUE TITLE
How to delete some features?

### ISSUE THREAD

**Issue by Maj-ew** [Hellsing/ModAPI-Mods#13]
I have problem with trees, I can't destroy them with axe when I am not hosting, and when I do host then I can't see trees when I get close to them.
So I wanted to somehow delete all related functions so I will be able to play and use this mode cause it's good.
cause Ultimate Cheat Menu doesn't work for me

**Comment by Hellsing** [comment]
All mods in here are discontinued. You would have to figure out your own how to delete certain parts of it. The mods are so out of date that I can't even give proper instructions on how to update the mods.
