### ISSUE TITLE
[bug] GriefClientPro - Aura - no effect on enemies at any radius

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [Hellsing/ModAPI-Mods#4]
Hi there,

I've tried adjusting it many times and it just won't kill the muties, haven't tested on players, it still works to repair stuff though. (MP tested, only your mod as with all my issue posts tested only your mod installed.)

Thanks

**Comment by Hellsing** [comment]
Fixed in latest release

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
woo fancy, thanks.
